apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: devops-prod
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
        - name: order-service
          image: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/devops-showcase/order-service:latest
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "5000"
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:4000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: devops-prod
spec:
  selector:
    app: order-service
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP